server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: h5-xyqb-platform
  profiles:
    active: dev
  data:
    mongodb:
      auto-index-creation: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
