spring:
  data:
    mongodb:
      uri: mongodb://qa:qatest@172.24.192.9:31460/h5_xyqb?authSource=admin

logging:
  level:
    root: INFO
    com.xyqb.platform: DEBUG
    org.springframework.data.mongodb: DEBUG
